### PR TITLE
Adds auth to homepage

### PR DESCRIPTION
**Pull request by 2KAbhishek**
Signed in
image

Signed out

image

Adds auth to home page
Enables auth based specs

### CODE REVIEW

**Comment by niravchavda99** [comment]
LGTM

**Comment by 2KAbhishek** [comment]
@niravchavda99 approve bhi kar do :D

**Review by niravchavda99 — APPROVED** [review]
LGTM

**Review by omjogani — APPROVED** [review]
Looks good!

**Pull request merged**
